version: '2'

services:
  prometheus:
    image: registry.cn-beijing.aliyuncs.com/k7scn/prometheus:2-debian-10
    container_name: prometheus
    network_mode: host
    ports:
      - '9090:9090'
    volumes:
      - ./conf:/conf
    command:
    - --config.file=/conf/prometheus.yml
    - --storage.tsdb.path=/opt/bitnami/prometheus/data
    - --web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries
    - --web.console.templates=/opt/bitnami/prometheus/conf/consoles
    - --web.enable-admin-api
    - --web.enable-lifecycle

  grafana:
    image: registry.cn-beijing.aliyuncs.com/k7scn/grafana:8-debian-10
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=admin'
    volumes:
      - grafana_data:/opt/bitnami/grafana/data

volumes:
  grafana_data:
    driver: local