version: '2'

services:
  consul:
    image: registry.cn-beijing.aliyuncs.com/k7scn/consul:1-debian-10
    container_name: consul
    volumes:
      - consul_data:/bitnami/consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
  consul-exporter:
    image: registry.cn-beijing.aliyuncs.com/k7scn/consul-exporter:0-debian-10
    container_name: consul-exporter
    network_mode: host
    ports:
      - 9107:9107
volumes:
  consul_data:
    driver: local
