global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'consul'
    static_configs:
      - targets: ['127.0.0.1:9107']
  - job_name: 'etcd'
    static_configs:
      - targets: ['127.0.0.1:2379']
  - job_name: 'minio'
    static_configs:
      - targets: ['127.0.0.1:9001']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['127.0.0.1:9216']
  - job_name: 'mysql'
    static_configs:
      - targets: ['127.0.0.1:9104']
  - job_name: 'redis'
    static_configs:
      - targets: ['127.0.0.1:9121']
