version: '3.7'

services:
  adguardhome:
    image: registry.cn-beijing.aliyuncs.com/k7scn/adguardhome:edge
    container_name: adguardhome
    network_mode: host  
    ports:
      - '53:53'
      - '3000:3000'
    volumes:
      - 'work_data:/opt/adguardhome/work'
      - 'conf_data:/opt/adguardhome/work'

  adguardhome-exporter:
    container_name: adguardhome-exporter
    image: registry.cn-beijing.aliyuncs.com/k7scn/adguard_exporter:latest
    ports:
      - "9617:9617"
    environment:
      - adguard_protocol=http
      - adguard_hostname=192.168.10.252
      - adguard_username=admin
      - adguard_password=/run/secrets/my-adguard-pass
      - adguard_port= #optional
      - interval=10s
      - log_limit=10000

volumes:
  work_data:
    driver: local
  conf_data:
    driver: local