version: '2'

services:
  redis:
    image: registry.cn-beijing.aliyuncs.com/k0s/redis:6.0-debian-10
    container_name: redis
    environment:
      - REDIS_PASSWORD=ookeVeivahkaeziech3r
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    network_mode: host  
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  redis-exporter:
    container_name: redis-exporter
    image: registry.cn-beijing.aliyuncs.com/k0s/redis-exporter:1-debian-10
    environment:
      - REDIS_ADDR=redis://127.0.0.1:6379
      - REDIS_PASSWORD=ookeVeivahkaeziech3r
    ports:
      - 9121:9121 
    network_mode: host  

volumes:
  redis_data:
    driver: local
