name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Consul
        run: docker-compose -f consul/docker-compose.yml up -d 
      - name: Etcd
        run: docker-compose -f etcd/docker-compose.yml up -d 
      - name: Minio
        run: docker-compose -f minio/docker-compose.yml up -d 
      - name: MongoDB
        run: docker-compose -f mongodb/docker-compose.yml up -d 
      - name: Mysql
        run: docker-compose -f mysql/docker-compose.yml up -d 
      - name: redis
        run: docker-compose -f redis/docker-compose.yml up -d 
      - name: prometheus
        run: docker-compose -f prometheus/docker-compose.yml up -d 
      - name: check
        run: docker ps -a